name: Reusable Java CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/masatake0511/build-java:0.0.3

    steps:
      # 呼び元リポジトリがチェックアウトされる
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: uses: masatake0511/pipeline-template/.github/actions/build/java@main
