name: Reusable Java CI

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version"
        required: false
        type: string
        default: "17"
      gradle-task:
        description: "Gradle task to run"
        required: false
        type: string
        default: "build"

jobs:
  build:
    runs-on: ubuntu-latest

    # ★ ここがポイント：Docker Actionではなく job.container
    container:
      image: ghcr.io/masatake0511/build-java:0.0.2

    steps:
      # 呼び元リポジトリがチェックアウトされる
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show environment (debug)
        run: |
          java -version
          pwd
          ls -la

      - name: Gradle build
        run: |
          ./gradlew ${{ inputs.gradle-task }}
